// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CountUniqueC
NumericVector CountUniqueC(NumericVector value, NumericVector group);
RcppExport SEXP _CommonFunctions_CountUniqueC(SEXP valueSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(CountUniqueC(value, group));
    return rcpp_result_gen;
END_RCPP
}
// GenerateGroup
NumericVector GenerateGroup(NumericVector id, NumericVector start, NumericVector end);
RcppExport SEXP _CommonFunctions_GenerateGroup(SEXP idSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(GenerateGroup(id, start, end));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CommonFunctions_CountUniqueC", (DL_FUNC) &_CommonFunctions_CountUniqueC, 2},
    {"_CommonFunctions_GenerateGroup", (DL_FUNC) &_CommonFunctions_GenerateGroup, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CommonFunctions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
