# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
findTrailingZeros <- function(n) {
    .Call('_CommonFunctions_findTrailingZeros', PACKAGE = 'CommonFunctions', n)
}

#' @export
CountUniqueC <- function(value, group) {
    .Call('_CommonFunctions_CountUniqueC', PACKAGE = 'CommonFunctions', value, group)
}

#' @export
GenerateGroup <- function(id, start, end) {
    .Call('_CommonFunctions_GenerateGroup', PACKAGE = 'CommonFunctions', id, start, end)
}

